theme:
  name: material
  palette:
    primary: indigo  # 원하시는 팩션 테마 컬러로 변경 가능
    accent: indigo
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - navigation.tabs
    - navigation.sections
